projectsveltos/libsveltos

api/v1alpha1/accessrequest_type.go, config/crd/bases/lib.projectsveltos.io_accessrequests.yaml, lib/crd/accessrequests.go
=> Fix AccessRequest CRD

api/v1alpha1/accessrequest_type.go
This label is added to any Secret generated for an AccessRequest
=> Introduce AccessRequestLabelName

lib/deployer/request_interface.go
Due to incorrect PR, deployer was not implementing the DeployerInterface anymore
=> Fix deployer

lib/deployer/fake/client.go
Fix fake deployer interface so it implements again the DeployerInterface.
=> Fake deployer

api/v1alpha1/debuggingconfiguration_types.go, config/crd/bases/lib.projectsveltos.io_debuggingconfigurations.yaml, lib/crd/debuggingconfigurations.go
New component for setting log severity
=> Introduce SveltosCluster-Manager

api/v1alpha1/classifierreport_types.go, api/v1alpha1/sveltoscluster_type.go, config/crd/bases/lib.projectsveltos.io_classifierreports.yaml, lib/crd/classifierreports.go
Move ClusterType definition in libsveltos
=> Add cluster type field to classifierReport

api/v1alpha1/debuggingconfiguration_types.go
This reverts commit 4ac3186b58e30da93cd2ef119668e43b5e78b9af.
=> Revert "Fix component names"

lib/deployer/utils.go
Sveltos resources (ClusterProfile and RoleRequest) references ConfigMaps/Secrets.
Resources contasined in referenced ConfigMap/Secrets are deployed in matching managed clusters.
A ConfigMap/Secret can be referenced by multiple Sveltos resources. That means, resources contained in such ConfigMap/Secret, are deployed due to multiple reasons. Each reason is a Sveltos resource referencing such ConfigMap/Secret.
Only when no more Sveltos resources are referencing the ConfigMap/Secret, policies contained in it can be withdrawn.
=> Move AddOwnerReference to libsveltos

lib/deployer/utils.go, lib/deployer/utils_test.go
Move owner check to libsveltos
=> Expose ConflictError

lib/deployer/utils.go, lib/roles/roles.go, lib/roles/roles_test.go
If Secret already exists, make sure owner is added as one of the OwnerReferences.
=> Add ownerReference as part of CreateSecret

api/v1alpha1/clusterhealthcheck_type.go, config/crd/bases/lib.projectsveltos.io_clusterhealthchecks.yaml, lib/crd/clusterhealthchecks.go
This type of liveness check refers to HealthCheck.
=> Add LivenessCheck type HealthCheck

api/v1alpha1/clusterhealthcheck_type.go
This reverts commit a1836d4dd29fe4e12095cc54b8cf35ce1ab020e4.
=> Revert "ClusterHealthCheck feature"

api/v1alpha1/rolerequest_type.go, config/crd/bases/lib.projectsveltos.io_rolerequests.yaml, lib/crd/rolerequests.go
ServiceAccountNamespace and ServiceAccountName are required fields.
=> RoleRequest required fields:

api/v1alpha1/common_types.go
This const is used by both addon-controller and event-manager
=> Move PolicyTemplate annotation to libsveltos

api/v1alpha1/sveltoscluster_type.go, config/crd/bases/lib.projectsveltos.io_sveltosclusters.yaml, lib/clusterproxy/clusterproxy.go, lib/clusterproxy/clusterproxy_test.go, lib/crd/sveltosclusters.go
=> feat(sveltoscluster): kubeconfigname override field

lib/deployer/worker.go, lib/deployer/worker_test.go
When adding job back to queue, also copy options
=> Fix store result

lib/clusterproxy/cluster_utils.go, lib/clusterproxy/cluster_utils_test.go
Both GetMatchingClusters and GetListOfClusters now accept a namespace. If namespace is not empty, only clusters in that namespace will be considered.
=> Filter clusters by namespace

api/v1alpha1/classifier_types.go, api/v1alpha1/common_types.go, api/v1alpha1/eventsource_type.go, config/crd/bases/lib.projectsveltos.io_classifiers.yaml, config/crd/bases/lib.projectsveltos.io_eventsources.yaml, lib/crd/classifiers.go, lib/crd/eventsources.go
- ResourceSelector containing Lua function is renamed to Evaluate;
- EventSource AggregatedSelection field comment includes what the Lua function should return;
- Classifier AggregatedClassification field comment includes what the Lua function should return;
=> Polish CRDs: renaming some of the fields and comments

lib/clusterproxy/cluster_utils.go
=> Check for nil selector

lib/clusterproxy/cluster_utils.go, lib/clusterproxy/cluster_utils_test.go
- SveltosCluster is ready if Status.Ready is set to true
- ClusterAPI powered cluster is ready if Status.ControlPlaneReady is set to true
=> Add utility to check if cluster is ready

.github/workflows/main.yaml, go.mod, go.sum, hack/tools/go.mod
This PR also bumps go modules.
=> Advance to go v1.22.0

api/v1alpha1/clusterhealthcheck_conversion.go, api/v1alpha1/conversion_test.go, api/v1alpha1/fuzz_test.go
When a LivenessChecks is referencing an HealthCheck, convert the APIVersion
=> ClusterHealthCheck conversion

lib/clusterproxy/cluster_utils.go
Do not check if version matches.
=> Check only if Group matches

lib/clusterproxy/clusterproxy.go
Instead of resetting the Data section, just add/update the entry with kubeconfig.
=> (feat) when updating Secret with kubeconfig add entry

lib/telemetry/data.go
Add number of configured profiles.
=> (feat) telemetry add configuration data

api/v1beta1/common_types.go, api/v1beta1/eventsource_type.go, config/crd/bases/lib.projectsveltos.io_eventsources.yaml, lib/crd/eventsources.go, manifests/apiextensions.k8s.io_v1_customresourcedefinition_eventsources.lib.projectsveltos.io.yaml
This PR changes the comments of those fields.
=> (feat) EventSource MessaggingCriteria supports regular expression

lib/deployer/utils_test.go, lib/logsettings/logsettings.go
Use debuggingConfiguration v1beta1
=> (chore) Register for log level

lib/crd/watcher.go
=> Remove panic from CRD watcher setup

lib/pullmode/utils.go
For every create/delete logs the pair ConfiguratationGroup and Requestor name
=> (chore) log ConfigurationGroup/Requestor

api/v1beta1/zz_generated.deepcopy.go, lib/pullmode/utils.go
When creating a ConfigurationBundle, reset the UID of any resource stored in it
=> (bug) ConfigurationBundle: reset UID

api/v1beta1/eventreport_type.go
Reverts projectsveltos/libsveltos#521
=> Revert "(chore) Add new label for EventReport"

lib/pullmode/manager.go
Order is important. Code was incorrectly using libsveltosset.Set which is a map, so effectively loosing the order.
Replaced it with a slice of corev1.ObjectReferences
=> (bug) List of staged ConfigurationBundles for a ConfigurationGroup

lib/deployer/applier.go
- normalize object
- remove Sveltos hash annotation
=> (bug) Optmize ComputePolicyHash

api/v1beta1/accessrequest_type.go, config/crd/bases/lib.projectsveltos.io_accessrequests.yaml, internal/test/helpers/external/cluster-api-const.go, lib/cel/cel_suite_test.go, lib/clusterproxy/cluster_utils.go, lib/clusterproxy/cluster_utils_test.go, lib/clusterproxy/clusterproxy.go, lib/clusterproxy/clusterproxy_test.go, lib/crd/accessrequests.go, lib/crd/crd_suite_test.go, lib/deployer/deployer_suite_test.go, lib/k8s_utils/utils_suite_test.go, lib/logsettings/logsettings_suite_test.go, lib/predicates/clusters.go, lib/predicates/clusters_test.go, lib/template/referenced_resource_test.go, manifests/apiextensions.k8s.io_v1_customresourcedefinition_accessrequests.lib.projectsveltos.io.yaml
Reverts projectsveltos/libsveltos#556
=> Revert "(chore) postpone advancing to clusterAPI core v1beta2"
