projectsveltos/libsveltos

- api/v1alpha1/classifierreport_types.go
When Classifier agent is configured to send ClassifierReports back to management cluster, that Secret contains kubeconfig to do so.
> Add Secret information

- api/v1alpha1/classifier_types.go
Those info are used by both classifier and classifier-agent pods.
> Add ClassifierReport info

- api/v1alpha1/cluster_type.go
- config/crd/bases/lib.projectsveltos.io_clusters.yaml
- lib/crd/clusters.go
As for ClusterAPI clusters, an imported cluster can be marked as paused. No addons will be deployed while cluster is set to paused.
> Add Paused as Cluster field

- api/v1alpha1/classifier_types.go
Changed utility api to contain cluster type as well to avoid collision if CAPI Cluster and SveltosCluster in same namespace have same name.
Added another utility to provide the labels that need to be set on ClassifierReport.
> ClassifierReport name

- lib/deployer/deployer_suite_test.go
- lib/deployer/utils.go
- lib/deployer/utils_test.go
ClusterProfile and RoleRequest both references ConfigMaps/Secrets containing policies that need to be deployed in matching clusters.
All resources contained in a referenced ConfigMap/Secret are deployed in a matching managed cluster.
Because same resource contained in a ConfigMap/Secret, can also be contained in other referenced ConfigMaps/Secrets, before deploying a resource in a matching cluster following validation is needed: 1) validate resource is not already present;
2) if resource is already present, validate that it was contained by the same referenced ConfigMap/Secret trying to deploy it now.
This code was originally in sveltos-manager. Given RoleRequest needs same validation, moving it (along with Labels/Annotation) in libsveltos.
> Move ValidateObjectForUpdate to libsveltos

- lib/roles/export_test.go
- lib/roles/roles.go
- lib/roles/roles_suite_test.go
- lib/roles/roles_test.go
Platform admin can create RoleRequest to grant tenant admins permissions in managed clusters.
When a RoleRequest is created, Sveltos creates:
1. ClusterRoles/Roles
2. ClusterRoleBindings/RoleBindings
3. ServiceAccount
in managed clusters.
Then for each pair tenant admin/cluster, a Secret is created containing the kubeconfig to access the managed cluster on behalf of the tenant admin.
This PR contains utilities needed for different sveltos services to manage those secrets.
> Add utilities for role secrets

- lib/deployer/client.go
- lib/deployer/client_test.go
- lib/deployer/fake/client.go
- lib/deployer/request_interface.go
- lib/deployer/utils.go
- lib/deployer/utils_test.go
- lib/deployer/worker.go
- lib/deployer/worker_test.go
- lib/logsettings/logsettings.go
- lib/logsettings/logsettings_suite_test.go
- lib/logsettings/logsettings_test.go
- lib/roles/roles.go
- lib/roles/roles_suite_test.go
- lib/roles/roles_test.go
A Secret containing Kubeconfig for a pair admin/cluster can be created because of multiple reasons. So add ownerReferences for ref counting purposes.
> Add onwerReferences to secret created for roles

- api/v1alpha1/policyref.go
- config/crd/bases/lib.projectsveltos.io_rolerequests.yaml
- lib/crd/rolerequests.go
It is not required to set namespace anymore when referencing a ConfigMap or Secret.
If namespace is set, it uniquely identifies a ConfigMap/Secret. If namespace is not set, at the time of deployment, the namespace will be implicity set to cluster namespace.
> PolicyRef namespace

- api/v1alpha1/clusterhealthcheck_type.go
- config/crd/bases/lib.projectsveltos.io_clusterhealthchecks.yaml
- lib/crd/clusterhealthchecks.go
Name must be unique among all LivenessChecks in a ClusterHealthChecks Name must be unique among all Notifications in a ClusterHealthCheck
> Add name to LivenessCheck and Notification

- api/v1alpha1/clusterhealthcheck_type.go
- config/crd/bases/lib.projectsveltos.io_clusterhealthchecks.yaml
- lib/crd/clusterhealthchecks.go
This type of notification will send a slack message on the specified channel when clusterHealthCheck liveness checks change
> Add slack notification type

- api/v1alpha1/clusterhealthcheck_type.go
Differentiate between deploying/removing resources in managed clusters vs evaluating liveness checks and sending notifications
> ClusterHealthCheck feature

- lib/roles/roles.go
Different components use this:
1. access-manager to create a ServiceAccount in managed cluster (starting from RoleRequest);
2. sveltos-agent when collecting events and evaluating health checks created by a tenant admin
> Move GetServiceAccountNameInManagedCluster to libsveltos

- api/v1alpha1/debuggingconfiguration_types.go
- config/crd/bases/lib.projectsveltos.io_debuggingconfigurations.yaml
- lib/crd/debuggingconfigurations.go
- lib/logsettings/logsettings_suite_test.go
- lib/logsettings/logsettings_test.go
For log settings, DebuggingConfiguration CRD, the component name for addon-manager is AddonManager
> Rename addon-manager component

- api/v1alpha1/addonconstraint_type.go
Cluster addons are deployed by addon controller.
Cluster addon constraints are loaded by addon-constraint controller. When new cluster is created it might match both a ClusterProfile and an AddonConstrain.
Matching a ClusterProfile means addons need to be deployed (by addon controller).
Matching an AddonConstraint means some validations are defined and any addon deployed in this cluster should satisfy those validations.
We need a sistem that allows addon constraints to be loaded before any addon is deployed.
Addon-constraint controller will add this annotation to any cluster it is aware of (if addon-constrain controller is aware of a cluster we can assume validations for such cluster are loaded).
Addon controller won't deploy any addons till this annotation is set on a cluster.
> Cluster annotation for addon constraint

- lib/clusterproxy/clusterproxy.go
- lib/clusterproxy/clusterproxy_test.go
ClusterAPI powered cluster is considered ready if either one of those conditions are true:
1. Condition ControlPlaneInitialized is set to true on the Cluster instance
2. Status.ControlPlaneReady is set to true
> Is cluster ready: check for ControlPlaneInitialized condition

- lib/clusterproxy/cluster_utils.go
- lib/clusterproxy/cluster_utils_test.go
- lib/clusterproxy/clusterproxy_test.go
When listing all clusters, add a check to verify if clusterapi is deployed in the management cluster.
Prior this commit, if clusterAPI was not present in the management cluster, list all clusters used to fail with
```
failed to get API group resources: unable to retrieve the complete list of server
APIs: cluster.x-k8s.io/v1beta1:"
```
> List all clusters

- .github/workflows/main.yaml
- lib/clusterproxy/cluster_utils.go
- lib/clusterproxy/cluster_utils_test.go
- lib/sharding/sharding_suite_test.go
- lib/sharding/utils.go
- lib/sharding/utils_test.go
This PR introduces:
1. the annotation to add to clusters to shard them
2. utility functions needed by controllers to get clusters filtering by shard and detecting whether a cluster belongs to a given shard
In general, a cluster with the annotation
```
sharding.projectsveltos.io/key: <shard-value>
```
will only be managed by the controller started explicitly for that shard.
A cluster with no annotation will be managed by the default controller.
> Introducing sharding for sveltos controller

- api/v1alpha1/debuggingconfiguration_types.go
New controller, shard-controller, is being introduced in Sveltos. This controller will be responsible for managing cluster shards.
As for any other sveltos component, the log severity can be programmatically configured. So add option to support that.
> Add ComponentShardController

- api/v1alpha1/clusterhealthcheck_type.go
- config/crd/bases/lib.projectsveltos.io_clusterhealthchecks.yaml
- lib/crd/clusterhealthchecks.go
part one of three PRs that would add the enhancement of allowing healthcheck-manager to send notifications to Microsoft Teams channels.
> add MS teams as notification type

- lib/clusterproxy/cluster_utils.go
- lib/clusterproxy/cluster_utils_test.go
- lib/clusterproxy/clusterproxy.go
This is a behavior change. Previoulsy, only deleted clusters were not considered.
> Matching clusters: only cluster ready to be programmed can be a match

- lib/deployer/utils.go
- lib/deployer/utils_test.go
A Kubernetes resource can be deployed in a managed cluster only by a ClusterProfile/Profile instance
Before this PR, if two ClusterProfile/Profile instances:
1. matched the same cluster
2. referenced the same ConfigMap
the resources contained in the ConfigMap were successfully deployed and neither of the ClusterProfile/Profile instance reported an error.
After this PR, the resources contained in the ConfigMap will still be successfully deployed. But while the first ClusterProfile/Profile will succeed, the second one will report a conflict with the first one.
This behavior change is implemented as part of introducing the concept of tier in ClusterProfile/Profile.
Allowing only one ClusterProfile/Profile instance to deploy a given Kubernetes resources, allows to handle the scenario where …
> Deployed resource validation

- lib/deployer/utils.go
- lib/deployer/utils_test.go
Instead of returning a boolen indicating whether resource exists or not, return the resource version (only existing objects have that field set).
> ValidateObjectForUpdate: Return resource version

- lib/clusterproxy/cluster_utils.go
- lib/clusterproxy/cluster_utils_test.go
An empty clusterSelector will match no cluster. This keeps behavior consistent with v1alpha1
Closes #317
> Empty ClusterSelector

- Makefile
- api/v1alpha1/resourcesummary_type.go
- api/v1alpha1/zz_generated.conversion.go
- api/v1beta1/resourcesummary_type.go
- config/crd/bases/lib.projectsveltos.io_resourcesummaries.yaml
- go.mod
- lib/crd/resourcesummaries.go
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_resourcesummaries.lib.projectsveltos.io.yaml
Add field
```yaml
// IgnoreForConfigurationDrift indicates to not track resource
// for configuration drift detection.
IgnoreForConfigurationDrift bool `json:"ignoreForConfigurationDrift"`
```
to Resource. Drift detection manager won't track any resource with such field set for configuration drift
[Story](https://github.com/projectsveltos/addon-controller/issues/612)
> (feat) Add ability to ignore resource for configuration drift

- lib/patcher/patcher.go
- lib/patcher/patcher_test.go
When multiple resources had to be patched there was an issue. This PR fixes it.
```bash
wget https://github.com/fluxcd/flux2/releases/download/v2.3.0/install.yaml
kubectl create configmap install-flux --from-file=install.yaml
```
Then create a ClusterProfile referencing above ConfigMap with patches
```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
name: fluxcd
spec:
clusterSelector:
matchLabels:
env: fv
syncMode: ContinuousWithDriftDetection
policyRefs:
- name: install-flux
namespace: default
kind: ConfigMap
patches:
- target:
kind: Namespace
name: ".*"
patch: |
- op: add
path: /metadata/labels/type
value: operator
```
all resources are deployed. Snipped from ClusterSummary:
```yaml
status:
dependencies: no dependencies
deployedGVKs:
- …
```
> (bug) pre deployment patching

- api/v1alpha1/sveltoscluster_type.go
- api/v1alpha1/zz_generated.conversion.go
- api/v1beta1/sveltoscluster_type.go
- config/crd/bases/lib.projectsveltos.io_sveltosclusters.yaml
- lib/crd/sveltosclusters.go
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_sveltosclusters.lib.projectsveltos.io.yaml
Sveltos periodically attempts to connect to managed SveltosClusters. Upon successful initial connection, the `Ready` status is set to true and remains unchanged.
To indicate connection health, this PR introduces a `ConnectionStatus` field within the Status. This field can be either `Healthy` or `Down`. The status transitions to `Down` after a configurable number of consecutive connection failures, which defaults to three.
> (feat) Set connection status in SveltosCluster

- api/v1alpha1/common_types.go
- api/v1alpha1/zz_generated.conversion.go
- api/v1beta1/common_types.go
- config/crd/bases/lib.projectsveltos.io_classifiers.yaml
- config/crd/bases/lib.projectsveltos.io_eventsources.yaml
- config/crd/bases/lib.projectsveltos.io_healthchecks.yaml
- lib/crd/classifiers.go
- lib/crd/eventsources.go
- lib/crd/healthchecks.go
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_classifiers.lib.projectsveltos.io.yaml
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_eventsources.lib.projectsveltos.io.yaml
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_healthchecks.lib.projectsveltos.io.yaml
In several situation, an event is identified by the creation of a specific resource.
Add `name` to ResourceSelector to better handle this scenarion.
Before this PR, to watch for a specific resource, we had to write Lua code in the `evaluate` field.
With this PR, that is not needed anymore.
> (feat) Add name to ResourceSelector

- api/v1alpha1/sveltoscluster_type.go
- api/v1alpha1/zz_generated.conversion.go
- api/v1alpha1/zz_generated.deepcopy.go
- api/v1beta1/sveltoscluster_type.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/lib.projectsveltos.io_sveltosclusters.yaml
- lib/crd/sveltosclusters.go
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_sveltosclusters.lib.projectsveltos.io.yaml
When renewing the token, Sveltos can be passed the namespace/name of the ServiceAccount to renew the token for.
> Token renewal: specify ServiceAccount

- lib/crd/watcher_test.go
- lib/deployer/utils.go
- lib/deployer/utils_test.go
- lib/k8s_utils/utils.go
- lib/k8s_utils/utils_suite_test.go
- lib/k8s_utils/utils_test.go
- lib/patcher/patcher_test.go
- lib/roles/roles.go
- lib/roles/roles_test.go
That information is useful to display diff in case of update while in DryRun mode.
Rename the `utils` package to `k8s_utils`
> (feat) Enhance ResourceInfo to contain current deployed resource

- lib/sveltos_upgrade/sveltos_agent_upgrade.go
- lib/sveltos_upgrade/sveltos_agent_upgrade_test.go
If there is any issue, this PR adds the exact reason why compatibility checks are failing.
Before this PR there only was a message, "compatibility checks failed" with no extra information on why.
This PR logs:
1. whether ConfigMap is not found
2. whether the ConfigMap.Data is empty
3. whether the expected version is not matching the version in the ConfigMap
> (chore) enhance logging for compatibility checks

- api/v1alpha1/zz_generated.conversion.go
- api/v1beta1/sveltoscluster_type.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/lib.projectsveltos.io_sveltosclusters.yaml
- lib/crd/sveltosclusters.go
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_sveltosclusters.lib.projectsveltos.io.yaml
Readiness checks are evaluated only until a SveltosCluster reaches the ready state.  A SveltosCluster transitions to the ready state only when all readiness checks pass.
Once a cluster is in the ready state, liveness checks are evaluated periodically.  If all liveness checks pass, the cluster is considered healthy.
> (feat) rename clusterCheck to ReadinessChecks and LivenessChecks

- lib/clusterproxy/cluster_utils.go
- lib/clusterproxy/cluster_utils_test.go
- lib/clusterproxy/clusterproxy.go
- lib/clusterproxy/clusterproxy_test.go
Deploying Sveltos on a management cluster with hundreds of existing CAPI clusters results in all clusters being onboarded immediately. This can lead to a rapid creation of hundreds of sveltos-agent deployments in the management cluster, potentially causing performance issues.  Therefore, a gradual onboarding mechanism is preferable.
This pull request introduces such a mechanism.  By using an annotation, Sveltos can selectively identify which CAPI clusters to manage. When this annotation is specified, Sveltos will only onboard those CAPI clusters that have it.
This feature allows for gradual onboarding, which is particularly beneficial in management clusters with a large number of pre-existing CAPI clusters.
> (feat) Selectively onboard CAPI clusters

- lib/clusterproxy/cluster_utils.go
- lib/clusterproxy/cluster_utils_test.go
- lib/clusterproxy/clusterproxy.go
- lib/clusterproxy/clusterproxy_test.go
By using an annotation, Sveltos can selectively identify which CAPI clusters to manage. When this annotation is specified, Sveltos will only onboard those CAPI clusters that have it.
Sveltos now uses annotations for selective CAPI cluster management, rather than readiness checks. Previously, an annotation indicated cluster readiness. Now, readiness is determined independently, and the annotation acts as a filter: only ready clusters with the specified annotation are managed.
> (feat) use onboard annotation only to find matching clusters

- lib/mgmtagent/doc.go
- lib/mgmtagent/mgmtagent_suite_test.go
- lib/mgmtagent/utils.go
- lib/mgmtagent/utils_test.go
This commit adds a new package named _mgmtagent_.
This package provides utility functions and types specifically designed for Sveltos agents running within the management cluster. It includes functionality for:
- Identifying keys related to EventSource, HealthCheck, and Reloader resources in ConfigMaps.
- Generating keys for these resource types based on their names.
These utilities are intended to simplify the management of resources watched by the management cluster's sveltos-agent and align with the per-cluster ConfigMap strategy used by other Sveltos components.
> feat: mgmtagent package for agent in management cluster utilities

- api/v1beta1/zz_generated.deepcopy.go
- lib/mgmtagent/utils.go
- lib/mgmtagent/utils_test.go
When sveltos-agent is deployed in the management cluster, EventSource and HealthCheck instances are not copied to the managed cluster.
A per cluster ConfigMap is created containing the EventSource and HealthCheck instances meant to be evaluated in a given cluster.
This PR add helper methods to identify if an entry was created because of an EventTrigger instance or a ClusterHealthCheck instance.
> (feat) add helper methods for ConfigMap with EventSource/HealthCheck

- api/v1beta1/zz_generated.deepcopy.go
- lib/mgmtagent/utils.go
Fix name of the ConfigMap containing EventSource/HealthCheck and Reloader to watch for a given cluster
> (bug) sveltos-agent in management cluster

- lib/deployer/clean.go
When profile stops matching a cluster, resources deployed because of that profile are removed.
If profile StopMatchingBehavior is set to LeavePolicies, resources are left on cluster. But labels and annotations indicating reason those resources were deployed must be cleared.
This PR makes sure owner annotations are cleared.
> (bug) remove owner annotations

- lib/pullmode/apis.go
- lib/pullmode/apis_test.go
- lib/pullmode/manager.go
- lib/pullmode/utils.go
- lib/pullmode/utils_test.go
Keep track of staged ConfigurationBundles in memory to avoid cache synchronization issues.
Previously, the flow was:
1. Create ConfigurationBundles in cluster
2. Query ConfigurationBundles from Kubernetes
3. Create ConfigurationGroup based on query results
This caused race conditions where the cache didn't return all recently created ConfigurationBundles, leading to incomplete ConfigurationGroups. The staged resource manager maintains an in-memory store of created bundles, eliminating dependency on cache consistency and ensuring all staged resources are available when creating the ConfigurationGroup.
Add logs when staged resources are added/deleted
> (feat) introduce stagedResourceManager

- api/v1beta1/zz_generated.deepcopy.go
- lib/pullmode/apis_test.go
- lib/pullmode/utils.go
- lib/pullmode/utils_test.go
When creating a ConfigurationBundle for an helm chart store index as annotation not as label.
Label is limited to 63 characters for the value and depending on helm chart namespace, release name that limit was exceeded occasionally.
> (bug) store helm index as annotation

- lib/deployer/applier.go
- lib/pullmode/apis.go
- lib/pullmode/export_test.go
- lib/pullmode/manager.go
- lib/pullmode/utils.go
With previous implementation we used to get very frequently error like this
```
failureMessage: 'Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io
"policyreports.wgpolicyk8s.io": the object has been modified; please apply your
changes to the latest version and try again'
```
So replace Path, with combination of Get/Update
> Use separate function to update CRD

- lib/pullmode/utils.go
When preparing configurationBundle, reset managedFields for each resource stored in it
> (bug) ConfigurationBundle: reset ManagedFields

- api/v1beta1/zz_generated.deepcopy.go
- lib/crd/watcher.go
- lib/crd/watcher_test.go
WatchCustomResourceDefinition requires now an handler that can be passed the action (add/delete/modify) that happens on CRD being watched.
This is needed because most of the Sveltos services only require to act on add /delete and can ignore modify.
> CRD watcher

- lib/clusterproxy/cluster_utils.go
Before checking if a cluster is in pull mode, always make sure cluster type is SveltosCluster
> (bug) only SveltosClusters can be in pull mode

- api/v1beta1/configurationgroup_type.go
- config/crd/bases/lib.projectsveltos.io_configurationgroups.yaml
- lib/crd/configurationgroups.go
- manifests/apiextensions.k8s.io_v1_customresourcedefinition_configurationgroups.lib.projectsveltos.io.yaml
This PR adds the +listType=atomic marker to the ConfigurationItems field in the ConfigurationGroup CRD to ensure the order of items is preserved during serialization and deserialization.
This is important because the deployment sequence depends on the order of configuration items.
> (bug) Preserve order of ConfigurationItems by setting listType to atomic

- lib/pullmode/apis.go
- lib/pullmode/export_test.go
- lib/pullmode/utils.go
- lib/pullmode/utils_test.go
ConfigurationBundles created for a given ConfigurationGroup are kept in memory (in a slice, to keep order).
So adding and removing the label was un-necessary operation, remaining from the original implementation.
> Remove staged label
